### ISSUE TITLE
Why is it not possible to provide description and content for 400 status code?

### ISSUE THREAD

**Issue by GorgeousPuree** [omermecitoglu/next-openapi-route-handler#13]
```
export const { PUT } = defineRoute({
  operationId: 'updateOrder',
  method: 'PUT',
  summary: 'Update order',
  description:
    'Update order text fields. To update order images use /api/orders/images',
  tags: ['Orders'],
  requestBody: UpdatedOrderFieldsApiDTO,
  action: async ({}) => {
    // return handleServerActionResponseInApiRoute(
    //   await updateOrderHandler(body, true),
    //   200
    // );
    return Response.json(null, { status: 501 });
  },
  responses: {
    201: { description: 'Order fields updated successfully' },
    400: {
      description:
        'Invalid request params or order cannot be updated for the reason described in the error message',
      content: AaaApiErrorDTO,
    },
    403: {
      description: 'No access to selected club location',
    },
    501: { description: 'Method not implemented' },
  },
  handleErrors: (errorType, issues) => {
    return apiRouteErrorHandler(errorType, issues);
  },
});

export const AaaApiErrorDTO = z.object({
  errorMessage: z.string(),
  validationErrors: ValidationErrorDTO.array().optional(),
});
```

Providing description and content for 400 status will not work, because library handles Bad Requests differently, ignoring content and description:
```
export function addBadRequest(queryParams?: unknown, requestBody?: unknown) {
  if (!queryParams && !requestBody) return undefined;
  return { description: "Bad Request" } as ResponseObject;
}
```
https://github.com/omermecitoglu/next-openapi-route-handler/blob/main/src/core/responses.ts

In case of 400, my endpoint returns an explanation why request failed. I would want to have my Error schema in OpenAPI json docs as well, but I can't due to library design. Why was it designed like that?
![image](https://github.com/user-attachments/assets/be628f60-b1cf-4ae7-a175-a47818314389)

**Comment by omermecitoglu** [comment]
I'll see what I can do tomorrow

> Why was it designed like that?

Because I made this plugin only for myself in the beginning, then it started getting a good shape and I decided to share it with the community. So it might not be perfect.

> Providing description and content for 400 status will not work, because library handles Bad Requests differently

In this case, responses provided by the developer should override anything comes from the library.

**Comment by GorgeousPuree** [comment]
> Because I made this plugin only for myself in the beginning, then it started getting a good shape and I decided to share it with the community. So it might not be perfect.

Understood.

I think removing this portion from https://github.com/omermecitoglu/next-openapi-route-handler/blob/main/src/core/definer.ts
should be enough?
```
  const response400 = addBadRequest(input.queryParams, input.requestBody);
  if (response400) {
    responses["400"] = response400;
  }
```
